version: '3.9'
services:
  mlog-api:
    env_file:
      - .env.dev
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app

  frontend:
    command: sh -lc "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:8000

  redis:
    volumes:
      - redis-data:/data

volumes:
  frontend-node_modules:
  redis-data:
