version: '3.9'
services:
  mlog-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mlog
      - ENV=dev
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - mlog-api
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  mongo-data:
